### ISSUE TITLE
Missing container argument

### ISSUE THREAD

**Issue by rbiggs** [brodybits/hyperapp-api-demo-on-inferno-and-ultradom#3]
The function `startViewRenderUltradom` should have an argument for container the way `app` does in Hyperapp and `patch` does in Ultradom. Otherwise, the way it is now it only appends the view to the body tag. If no container is provided you could default to document.body. And you could be a little nice to users by letting them use a query selector to indicate the container:

```javascript
function startViewRenderUltradom(initState, actions, view, container) {
   if (container && typeof container === 'string') container = document.querySelector(container)
   else if (!container) container = document.body

  // Later, append view to container:
  container.appendChild(myViewState.element)
}
```

With this change, you can get your example to render inside the div with id of root as in your example:

```javascript
startViewRenderUltradom(initState, actions, myview, '#root')
```

**Comment by brodybits** [comment]
Thanks @rbiggs for reporting, hoping to fix this one soon.
